name: acr-4
on:
  repository_dispatch:
    types:
      - manual-trigger
      - manual-trigger-acr
      - manual-trigger-acr-4
  schedule:
    - cron: '0 6 * * *'
jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Run OCI Distribution Spec conformance tests
        uses: opencontainers/distribution-spec@master
        env:
          OCI_ROOT_URL: https://shizhtest.azurecr.io
          OCI_NAMESPACE: ocitest
          OCI_USERNAME: ${{ secrets.ACR_USERNAME }}
          OCI_PASSWORD: ${{ secrets.ACR_PASSWORD }}
          OCI_TEST_CONTENT_MANAGEMENT: 1
          OCI_HIDE_SKIPPED_WORKFLOWS: 1
      - name: Upload test report to Azure Blob Storage
        run: azcopy --source report.html --destination https://shizhtest.blob.core.windows.net/distribution-spec/acr/content-management/report.html --dest-key ${{ secrets.AZURE_ACCESS_KEY }}
        if: always()
